kind: Template
apiVersion: v1
metadata:
  name: microservice-is-template-prod
  annotations:
    description: Image stream for Parksmap mircoservice - RHOCP Adv Dev Class - Production
labels:
  app: ${APPLICATION_NAME}
  createdBy: microservice-is-template-prod
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    dockerImageRepository: ''
    lookupPolicy:
      local: false
    tags:
    - name: 0.0-0        
parameters:
- description: 'The name for the application (must be unique in project)'
  name: APPLICATION_NAME
  required: true
