kind: Template
apiVersion: v1
metadata:
  name: mlbparks-dev
  annotations:
    description: MLB Parks application - RHOCP Adv Dev Class - NO Mongo DB - Development
labels:
  app: ${APPLICATION_NAME}
  createdBy: mlbparks-template-dev
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      build: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    runPolicy: Serial
    triggers:
    - type: Generic
      generic:
        secret: ${GENERIC_TRIGGER_SECRET}
    - type: GitHub
      github:
        secret: ${GITHUB_TRIGGER_SECRET}
    - type: ImageChange
      imageChange: {}
    source:
      binary: {}
      type: binary
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: jboss-eap64-openshift:1.7
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    dockerImageRepository: ''
    lookupPolicy:
      local: false
    tags:
    - name: 0.0-0
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      deploymentConfig: ${APPLICATION_NAME}
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: "docker-registry.default.svc:5000/${PROJECT}/${APPLICATION_NAME}:0.0-0"
          ports:
          - name: ${APPLICATION_NAME}-http
            containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: ${MLBPARKS_MEMORY_LIMIT}          
          readinessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/ws/info/"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1            
          livenessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/ws/healthz/"
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1                          
          envFrom: 
            - configMapRef:
                name: ${APPLICATION_NAME}
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      type: parksmap-backend
    annotations:
      description: The web server's http port
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- kind: ConfigMap             
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  data:
    DB_HOST: ${MONGODB_SERVICE_NAME}
    DB_PORT: "27017"
    DB_NAME: ${MONGODB_DATABASE}
    DB_PASSWORD: ${MONGODB_PASSWORD}
    DB_USERNAME: ${MONGODB_USER}
    APPNAME: ${APPLICATION_NAME}
parameters:
- description: 'The name for the application (must be unique in project)'
  name: APPLICATION_NAME
  value: mlbparks
- description: 'Custom hostname for service routes.  Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  name: APPLICATION_HOSTNAME
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci.apps.10.2.2.2.xip.io/content/groups/public/)
  name: MAVEN_MIRROR_URL
  displayName: Maven mirror url
  required: false
- description: Database name
  name: MONGODB_DATABASE
  value: parksmap
- description: Disable data file preallocation.
  name: MONGODB_NOPREALLOC
- description: Set MongoDB to use a smaller default data file size.
  name: MONGODB_SMALLFILES
- description: Runs MongoDB in a quiet mode that attempts to limit the amount of output.
  name: MONGODB_QUIET
- description: Database user name
  name: MONGODB_USER
  value: mongodb_user
- description: Database user password
  name: MONGODB_PASSWORD
  value: mongodb_password
- description: Database admin password
  name: MONGODB_ADMIN_PASSWORD
  value: mongodb_admin_password
  generate: expression
- description: Github trigger secret
  name: GITHUB_TRIGGER_SECRET
  from: '[a-zA-Z0-9]{8}'
  generate: expression
- description: Generic build trigger secret
  name: GENERIC_TRIGGER_SECRET
  from: '[a-zA-Z0-9]{8}'
  generate: expression
- description: Database service name
  name: MONGODB_SERVICE_NAME
  value: mongodb-internal
- description: Current project name (i.e. namespace)
  name: PROJECT
  required: true  
- description: mlbparks memory limit, e.g. 512Mi, 2Gi
  name: MLBPARKS_MEMORY_LIMIT
  required: true
  value: 2Gi
- description: 'Hostname for service routes e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME
  required: true
