kind: Template
apiVersion: v1
metadata:
  name: mlbparks-is-prod
  annotations:
    description: Image stream for MLB Parks application - RHOCP Adv Dev Class - NO Mongo DB - Production
labels:
  app: ${APPLICATION_NAME}
  createdBy: mlbparks-is-template-prod
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    dockerImageRepository: ''
    lookupPolicy:
      local: false
    tags:
    - name: 0.0-0        
parameters:
- description: 'The name for the application (must be unique in project)'
  name: APPLICATION_NAME
  value: mlbparks
