kind: Template
apiVersion: v1
metadata:
  name: parksmap
  annotations:
    description: Parksmap application - RHOCP Adv Dev Class - Development
labels:
  app: ${APPLICATION_NAME}
  createdBy: parksmap-template-dev
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: {APPLICATION_NAME}
    labels:
      build: {APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: {APPLICATION_NAME}:latest"
    runPolicy: Serial
    triggers:
    - type: Generic
      generic:
        secret: {GENERIC_TRIGGER_SECRET}
    - type: GitHub
      github:
        secret: {GITHUB_TRIGGER_SECRET}
    - type: ImageChange
      imageChange: {}
    source:
      binary: {}
      type: binary
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: redhat-openjdk18-openshift:1.2
        env:
        - name: MAVEN_MIRROR_URL
          value: {MAVEN_MIRROR_URL}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: {APPLICATION_NAME}
  spec:
    dockerImageRepository: ''
    tags:
    - name: 0.0-0
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: {APPLICATION_NAME}
    labels:
      deploymentConfig: {APPLICATION_NAME}
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: {APPLICATION_NAME}
    template:
      metadata:
        labels:
          deploymentConfig: {APPLICATION_NAME}
      spec:
        containers:
        - name: {APPLICATION_NAME}
          image: "docker-registry.default.svc:5000/${PROJECT}/${APPLICATION_NAME}:0.0-0"
          ports:
          - name: {APPLICATION_NAME}-http
            containerPort: 8080
            protocol: TCP
          - name: {APPLICATION_NAME}-ping
            containerPort: 8888
            protocol: TCP
          resources:
            limits:
              memory: ${NATPARKS_MEMORY_LIMIT}          
          readinessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1            
          livenessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1                          
          env:
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: {APPLICATION_NAME}-ping
          - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            value: '8888'
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
- kind: Route
  apiVersion: v1
  metadata:
    name: {APPLICATION_NAME}
    annotations:
      description: Route for application's http service
    labels:
      app: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME}
    to:
      name: ${APPLICATION_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    name: {APPLICATION_NAME}
    labels:
      type: parksmap-backend
    annotations:
      description: The web server's http port
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: {APPLICATION_NAME}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: parksmap
- description: 'Custom hostname for service routes.  Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  name: APPLICATION_HOSTNAME
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci.apps.10.2.2.2.xip.io/content/groups/public/)
  name: MAVEN_MIRROR_URL
  displayName: Maven mirror url
  required: false
- description: Current project name (i.e. namespace)
  name: PROJECT
  required: true  
- description: parksmap memory limit, e.g. 512Mi, 2Gi
  name: NATPARKS_MEMORY_LIMIT
  required: true
  value: 2Gi
- description: 'Hostname for service routes e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME
  required: true
