kind: Template
apiVersion: v1
metadata:
  name: parksmap
  annotations:
    description: Parksmap application - RHOCP Adv Dev Class - Production
labels:
  app: ${APPLICATION_NAME}
  createdBy: parksmap-template-prod
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      deploymentConfig: ${APPLICATION_NAME}
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: "docker-registry.default.svc:5000/${PROJECT}/${APPLICATION_NAME}:0.0-0"
          ports:
          - name: ${APPLICATION_NAME}-http
            containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: ${NATPARKS_MEMORY_LIMIT}          
          readinessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1            
          livenessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1                          
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    annotations:
      description: The web server's http port
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: parksmap
- description: 'Custom hostname for service routes.  Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  name: APPLICATION_HOSTNAME
- description: Current project name (i.e. namespace)
  name: PROJECT
  required: true  
- description: parksmap memory limit, e.g. 512Mi, 2Gi
  name: NATPARKS_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: 'Hostname for service routes e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME
  required: true
